name: quality

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  coding-standards:
    runs-on: ubuntu-latest
    name: Coding standards (PER-CS)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Check coding standards
        run: composer lint

  static-analysis:
    runs-on: ubuntu-latest
    name: Static analysis (PHPStan)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Run PHPStan
        run: composer analyse
